# Generated by Django 2.0.6 on 2019-05-19 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('book_number', models.IntegerField(blank=True, null=True)),
                ('subtotal', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'order_item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TAddress',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=10, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('column_8', models.CharField(blank=True, db_column='Column_8', max_length=10, null=True)),
            ],
            options={
                'db_table': 't_address',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TBooks',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('author', models.CharField(blank=True, max_length=20, null=True)),
                ('press', models.CharField(blank=True, max_length=30, null=True)),
                ('press_time', models.DateTimeField(blank=True, null=True)),
                ('edition', models.CharField(blank=True, max_length=20, null=True)),
                ('printing_time', models.DateTimeField(blank=True, null=True)),
                ('impression', models.CharField(blank=True, max_length=10, null=True)),
                ('isbn', models.CharField(blank=True, db_column='ISBN', max_length=20, null=True)),
                ('number', models.CharField(blank=True, max_length=20, null=True)),
                ('page_number', models.CharField(blank=True, max_length=20, null=True)),
                ('format', models.CharField(blank=True, max_length=20, null=True)),
                ('paper', models.CharField(blank=True, max_length=20, null=True)),
                ('pack', models.CharField(blank=True, max_length=20, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('dd_price', models.FloatField(blank=True, null=True)),
                ('recommend', models.CharField(blank=True, max_length=500, null=True)),
                ('introduce', models.CharField(blank=True, max_length=200, null=True)),
                ('author_intro', models.CharField(blank=True, max_length=200, null=True)),
                ('list', models.CharField(blank=True, max_length=200, null=True)),
                ('reviews', models.CharField(blank=True, max_length=200, null=True)),
                ('insert_map', models.CharField(blank=True, max_length=500, null=True)),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('shelf_time', models.DateTimeField(blank=True, null=True)),
                ('route', models.CharField(blank=True, max_length=50, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('is_sale', models.IntegerField(blank=True, null=True)),
                ('sales', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_books',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TOrder',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('tptal_price', models.FloatField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('column_7', models.CharField(blank=True, db_column='Column_7', max_length=10, null=True)),
            ],
            options={
                'db_table': 't_order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TSort',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('category', models.CharField(blank=True, max_length=20, null=True)),
                ('parent_id', models.IntegerField(blank=True, null=True)),
                ('number', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_sort',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TUser',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('u_email', models.CharField(blank=True, max_length=40, null=True)),
                ('u_name', models.CharField(blank=True, max_length=50, null=True)),
                ('password', models.CharField(blank=True, max_length=30, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_user',
                'managed': False,
            },
        ),
    ]
