# Generated by Django 2.0.6 on 2019-05-22 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dangdangapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='torder',
            options={},
        ),
    ]
