# Generated by Django 2.0.6 on 2019-05-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dangdangapp', '0003_auto_20190523_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuser',
            name='status',
            field=models.IntegerField(blank=True, default=False, null=True, verbose_name='是否确认'),
        ),
    ]
