# Generated by Django 2.0.6 on 2019-05-23 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dangdangapp', '0004_auto_20190523_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuser',
            name='status',
            field=models.BooleanField(default=False, verbose_name='是否确认'),
        ),
    ]
