# Generated by Django 2.0.6 on 2019-05-23 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dangdangapp', '0005_auto_20190523_1745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tuser',
            old_name='status',
            new_name='has_confirm',
        ),
    ]
