# Generated by Django 2.0.6 on 2019-05-25 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dangdangapp', '0006_auto_20190523_1747'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={},
        ),
        migrations.AlterModelOptions(
            name='taddress',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tbooks',
            options={},
        ),
        migrations.AlterModelOptions(
            name='torder',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tsort',
            options={},
        ),
        migrations.AlterField(
            model_name='tuser',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
